
---
title: "Projects"
author: "Chris Bunker"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_float: true
---

# My Projects

## 1. Covid-19 and Economic Status Project

This project is a continuation of a visualization project
I worked on in 690V. 

690V was a data visualization classes and was also one of
my first classes I took when starting my major, so there were many things to
fix. 

I am in the process of improving this project to submit for my final 
project for DACSS 604, using advice given by Professor Erico, adhering to
best practices, such as those outlined in Miller's book.

Within the content of the project, I investigate the relationship between the
Covid-19 pandemic and economic status for countries across the globe. I ask the
question: are impoverished countries disproportionately affected by Covid-19.
The visualizations within this project aim to uncover an answer.

- **GitHub Repository**: [Link to GitHub Repository](https://github.com/ProfessionalProfile)
- **Analysis Page**: [Standalone HTML Page](dashboard.html)

---


